[package]
name = "cfg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {  workspace = true }
serde_json ={ version = "1.0.x" }
bitflags = { workspace = true }

macros = {path = "../macros"}
luban_lib = { path = "../../luban_lib" }

bevy = { workspace = true }
thiserror = { workspace = true }
smallvec = { workspace = true }
