# [package]
# name = "terrain"
# version = "0.1.0"
# edition = "2021"

[workspace]
members = ["crates/*", "entries/*"]
resolver = "2"


[workspace.dependencies]
# bevy = { version = "0.12.0", features = ["trace", "trace_tracy", "embedded_watcher"] }
# lightyear = { version = "0.15.1", features = [] }

bevy = { version = "0.14.0-rc.3", features = ["file_watcher"] }
bevy_asset_loader = { path = "../bevy_asset_loader/bevy_asset_loader" }
bevy_asset_loader_derive = { path = "../bevy_asset_loader/bevy_asset_loader_derive" }

once_cell = "1.13.0"
# bevy_common_assets = { version = "0.10.0", features = ["toml"] }
serde = { version = "1.0.202", features = ["derive"] }
smallvec = { version = "1.13.2" }
thiserror = { version = "1.0.25" }

# bevy-persistent
# bevy-tnua
# big-brain
# Bevy Hanabi
# oxidized_navigation
# leafwing-input-manager

# bevy_xpbd_3d = { version = "0.4.2", features = ["simd"] } # "debug-plugin"
# bevy_xpbd_derive = "0.1.0"

# Enable a small amount of optimization in debug mode
[profile.dev]
opt-level = 1

# Enable high optimizations for dependencies (incl. Bevy), but not for our code:
[profile.dev.package."*"]
opt-level = 3

# [profile.release-with-debug]
# inherits = "release"
# debug = true

# can not patch cross version, otherwie plugin will not work.
# [patch.crates-io]
# bevy = { path = '../bevy' }
# bevy_math = { path = '../bevy/crates/bevy_math' }
