[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
bevy = { path = "E:/BevyProject/bevy", features = [
    "file_watcher",
    "embedded_watcher",
    "trace",
    "trace_tracy",
    "serialize",
    "free_camera",
] }
# Set max log levels. This helps avoid unwanted low-severity log spam, which can affect performance.
log = { version = "0.4", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
tracing = { version = "0.1", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
tracing-subscriber = { version = "0.3", features = [
    "env-filter",
    "fmt",
    "local-time",
] }
tracing-appender = { version = "0.2" }

wgpu = { version = "27.0" }
wgpu-types = { version = "27.0" }
encase = { version = "0.12" }
bytemuck = { version = "1.24" }

# 辅助功能
once_cell = { version = "1.21" }
serde = { version = "1.0", features = ["derive"] }
strum = { version = "0.27", features = ["derive"] }
bitflags = { version = "2.10", features = ["serde"] }
paste = { version = "1.0" }
time = { version = "0.3", features = ["formatting", "parsing"] }

# 主要是用于测试和示例
image = { version = "0.25" }
imageproc = { version = "0.25" }
crossbeam = { version = "0.8.4" }


# Idiomatic Bevy code often triggers these lints, and the CI workflow treats them as errors.
# In some cases they may still signal poor code quality however, so consider commenting out these lines.
[workspace.lints.clippy]
# Bevy supplies arguments to systems via dependency injection, so it's natural for systems to
# request more than 7 arguments -- which triggers this lint.
too_many_arguments = "allow"
# Queries that access many components may trigger this lint.
type_complexity = "allow"
# 屏蔽收缩式if警告
collapsible_if = "allow"
# 禁止 unwrap()
unwrap_used = "warn"
# 允许使用 panic!
panic = "allow"

# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

# Remove expensive debug assertions due to <https://github.com/bevyengine/bevy/issues/14291>
[profile.dev.package.wgpu-types]
debug-assertions = false

[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"

# Patch all bevy crates to use local repository
[patch.crates-io]
bevy = { path = "E:/BevyProject/bevy" }
bevy_a11y = { path = "E:/BevyProject/bevy/crates/bevy_a11y" }
bevy_android = { path = "E:/BevyProject/bevy/crates/bevy_android" }
bevy_animation = { path = "E:/BevyProject/bevy/crates/bevy_animation" }
bevy_anti_alias = { path = "E:/BevyProject/bevy/crates/bevy_anti_alias" }
bevy_app = { path = "E:/BevyProject/bevy/crates/bevy_app" }
bevy_asset = { path = "E:/BevyProject/bevy/crates/bevy_asset" }
bevy_audio = { path = "E:/BevyProject/bevy/crates/bevy_audio" }
bevy_camera = { path = "E:/BevyProject/bevy/crates/bevy_camera" }
bevy_color = { path = "E:/BevyProject/bevy/crates/bevy_color" }
bevy_camera_controller = { path = "E:/BevyProject/bevy/crates/bevy_camera_controller" }
bevy_core_pipeline = { path = "E:/BevyProject/bevy/crates/bevy_core_pipeline" }
bevy_derive = { path = "E:/BevyProject/bevy/crates/bevy_derive" }
bevy_dev_tools = { path = "E:/BevyProject/bevy/crates/bevy_dev_tools" }
bevy_diagnostic = { path = "E:/BevyProject/bevy/crates/bevy_diagnostic" }
bevy_dylib = { path = "E:/BevyProject/bevy/crates/bevy_dylib" }
bevy_ecs = { path = "E:/BevyProject/bevy/crates/bevy_ecs" }
bevy_encase_derive = { path = "E:/BevyProject/bevy/crates/bevy_encase_derive" }
bevy_feathers = { path = "E:/BevyProject/bevy/crates/bevy_feathers" }
bevy_gilrs = { path = "E:/BevyProject/bevy/crates/bevy_gilrs" }
bevy_gizmos = { path = "E:/BevyProject/bevy/crates/bevy_gizmos" }
bevy_gltf = { path = "E:/BevyProject/bevy/crates/bevy_gltf" }
bevy_image = { path = "E:/BevyProject/bevy/crates/bevy_image" }
bevy_input = { path = "E:/BevyProject/bevy/crates/bevy_input" }
bevy_input_focus = { path = "E:/BevyProject/bevy/crates/bevy_input_focus" }
bevy_internal = { path = "E:/BevyProject/bevy/crates/bevy_internal" }
bevy_light = { path = "E:/BevyProject/bevy/crates/bevy_light" }
bevy_log = { path = "E:/BevyProject/bevy/crates/bevy_log" }
bevy_macro_utils = { path = "E:/BevyProject/bevy/crates/bevy_macro_utils" }
bevy_math = { path = "E:/BevyProject/bevy/crates/bevy_math" }
bevy_mesh = { path = "E:/BevyProject/bevy/crates/bevy_mesh" }
bevy_pbr = { path = "E:/BevyProject/bevy/crates/bevy_pbr" }
bevy_picking = { path = "E:/BevyProject/bevy/crates/bevy_picking" }
bevy_platform = { path = "E:/BevyProject/bevy/crates/bevy_platform" }
bevy_post_process = { path = "E:/BevyProject/bevy/crates/bevy_post_process" }
bevy_ptr = { path = "E:/BevyProject/bevy/crates/bevy_ptr" }
bevy_reflect = { path = "E:/BevyProject/bevy/crates/bevy_reflect" }
bevy_remote = { path = "E:/BevyProject/bevy/crates/bevy_remote" }
bevy_render = { path = "E:/BevyProject/bevy/crates/bevy_render" }
bevy_scene = { path = "E:/BevyProject/bevy/crates/bevy_scene" }
bevy_shader = { path = "E:/BevyProject/bevy/crates/bevy_shader" }
bevy_solari = { path = "E:/BevyProject/bevy/crates/bevy_solari" }
bevy_sprite = { path = "E:/BevyProject/bevy/crates/bevy_sprite" }
bevy_sprite_render = { path = "E:/BevyProject/bevy/crates/bevy_sprite_render" }
bevy_state = { path = "E:/BevyProject/bevy/crates/bevy_state" }
bevy_tasks = { path = "E:/BevyProject/bevy/crates/bevy_tasks" }
bevy_text = { path = "E:/BevyProject/bevy/crates/bevy_text" }
bevy_time = { path = "E:/BevyProject/bevy/crates/bevy_time" }
bevy_transform = { path = "E:/BevyProject/bevy/crates/bevy_transform" }
bevy_ui = { path = "E:/BevyProject/bevy/crates/bevy_ui" }
bevy_ui_render = { path = "E:/BevyProject/bevy/crates/bevy_ui_render" }
bevy_ui_widgets = { path = "E:/BevyProject/bevy/crates/bevy_ui_widgets" }
bevy_utils = { path = "E:/BevyProject/bevy/crates/bevy_utils" }
bevy_window = { path = "E:/BevyProject/bevy/crates/bevy_window" }
bevy_winit = { path = "E:/BevyProject/bevy/crates/bevy_winit" }
