[workspace]
members = [
    "crates/atom_terrain",
    "crates/atom_ability",
    "crates/atom_cel_shader",
    "crates/atom_core",
    "crates/atom_data",
    "crates/atom_data_macros",
    "crates/atom_layertag",
    "crates/atom_math",
    "crates/atom_pqef",
    "crates/atom_render",
    "crates/atom_renderdoc",
    "crates/atom_shader_lib",
    "crates/atom_utils",
]
resolver = "3"

[workspace.package]
publish = false
license = "MIT OR Apache-2.0"

[workspace.dependencies]
bevy = { version = "0.19", features = [
    "file_watcher",
    "embedded_watcher",
    "trace",
    "trace_tracy",
    "serialize",
    "bevy_remote",
    "bevy_camera_controller",
    "free_camera",
] }
log = { version = "0.4", features = ["max_level_info"] }
tracing = { version = "0.1", features = ["max_level_info"] }
tracing-subscriber = { version = "0.3", features = ["local-time"] }
tracing-appender = { version = "0.2" }
time = { version = "0.3", features = ["local-offset", "formatting", "parsing"] }
bytemuck = { version = "1.24", features = ["derive"] }
crossbeam = { version = "0.8" }
once_cell = { version = "1.20" }
smallvec = { version = "1.13" }
thiserror = { version = "2" }
dotenv = { version = "0.15" }
paste = { version = "1.0" }
wgpu = { version = "29.0.3" }
wgpu-types = { version = "29.0.3" }
encase = { version = "0.12" }
image = { version = "0.25" }
imageproc = { version = "0.25" }
serde = { version = "1.0", features = ["derive"] }
bitflags = { version = "2.6" }

[patch.crates-io]
bevy = { path = "/data/codes/Bevy" }
bevy_app = { path = "/data/codes/Bevy/crates/bevy_app" }
bevy_asset = { path = "/data/codes/Bevy/crates/bevy_asset" }
bevy_reflect = { path = "/data/codes/Bevy/crates/bevy_reflect" }

[workspace.lints.clippy]
too_many_arguments = "allow"
type_complexity = "allow"
collapsible_if = "allow"
unwrap_used = "warn"
panic = "allow"


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
codegen-units = 1
lto = "thin"
debug = 1
