[package]
name = "ability_editor"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }
bevy-trait-query = "0.16.0"
bevy-trait-query-impl = "0.16.0"
smallvec = "1.15.1"
