[env]
# force all crates use root assets folder
BEVY_ASSET_ROOT = { value = "./", relative = true }

ATOM_ASSET_ROOT = { value = "./assets", relative = true }
ATOM_PROCESSED_ASSET_ROOT = { value = "./processed_assets", relative = true }

ATOM_SAVED_ROOT = { value = "./saved", relative = true }

ATOM_ROOT = { value = "./", relative = true }
