[package]
name = "macros"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
quote = "1.0.38"
syn = "2.0.96"
proc-macro2 = "1.0.93"

[lib]
proc-macro = true
