[package]
name = "terrain"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# 项目依赖
atom_core = { path = "../atom_core" }
atom_shader_lib = { path = "../atom_shader_lib" }
atom_render = { path = "../atom_render" }

# 公共核心库
bevy = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
tracing-appender = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
strum = { workspace = true }
bitflags = { workspace = true }
encase = { workspace = true }
paste = { workspace = true }
bytemuck = { workspace = true }
crossbeam = { workspace = true }
wgpu = { workspace = true }
wgpu-types = { workspace = true }

# 第三方依赖

[dev-dependencies]

[[example]]
name = "chunk_loader"
path = "examples/chunk_loader.rs"

[features]
# 默认是 cpu seam
default = []

[lints]
workspace = true
