[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# feature "wgpu_trace", "trace_chrome", "dynamic_linking", "wayland", 
# bevy_mod_debugdump = "0.7.0"
bevy = { workspace = true }

strum = { version = "0.25.0", features = ["derive", "strum_macros"] }
strum_macros = "0.25.3"
pqef = { path = "../pqef" }
project = { path = "../project" }

# noisy_bevy = { path = "../dep/noisy_bevy" }
# simdnoise = { path = "../../../dep/rust-simd-noise" }
# bevy_rapier3d = { path = "../dep/bevy_rapier/bevy_rapier3d" }
# bevy-inspector-egui = "0.18.0"
# bevy_editor_pls = "0.3.0"
# bevy_mod_debugdump = { path = "../dep/bevy_mod_debugdump" }
# bevy_terrain = { path = "../dep/bevy_terrain" }
rand = "0.8.5"
smallvec = "1.11.2"
futures-lite = "2.0.1"

noisy_bevy = "0.5.0"

bevy_obj = "0.12.0"

bevy_xpbd_3d = { version = "0.3.2", features = ["simd"] } # "debug-plugin"
bevy_xpbd_derive = "0.1.0"
bevy_replicon = "0.17.0"

# bevy_ecs_ldtk = "0.5.0"
# bevy_ecs_tilemap = "0.9.0"
# bevy_rapier2d = "0.20.0"

tracing-subscriber = { version = "0.3.18", features = [
    "registry",
    "env-filter",
    "json",
    "local-time"
] }
tracing-chrome = { version = "0.7.1", optional = true }
tracing-tracy = { version = "0.10.4", optional = true }
tracing-log = "0.2.0"
tracing-error = { version = "0.2.0", optional = true }
tracy-client = { version = "0.16", optional = true }
tracing-appender = { version = "0.2.3", features = []}
