[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# feature "wgpu_trace", "trace_chrome", "dynamic_linking", "wayland", 
# bevy_mod_debugdump = "0.7.0"
bevy = { workspace = true }
serde = { workspace = true }
# lightyear = { workspace = true }
# bevy_xpbd_3d = { workspace = true }
# bevy_xpbd_derive = { workspace = true }
smallvec = { workspace = true }

strum = { version = "0.26.3", features = ["derive", "strum_macros"] }
strum_macros = "0.26.4"
pqef = { path = "../pqef" }
project = { path = "../project" }

terrain_player_client = { path = "../terrain_player_client" }
terrain_core = { path = "../terrain_core" }
settings = { path = "../settings" }

rand = "0.8.5"
futures-lite = "2.3.0"

# noisy_bevy = "0.6.0"

# bevy_obj = "0.13.0"

# bevy_ecs_ldtk = "0.5.0"
# bevy_ecs_tilemap = "0.9.0"
# bevy_rapier2d = "0.20.0"

serde_json = "1.0.120"
# bevy-inspector-egui = "0.23.4"
bitflags = { workspace = true }
bitfield-struct = "0.8.0"
