[package]
name = "terrain"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# feature "wgpu_trace", "trace_chrome", "dynamic_linking", "wayland", 
# bevy_mod_debugdump = "0.7.0"
bevy = { workspace = true }
serde = { workspace = true }

strum = { version = "0.25.0", features = ["derive", "strum_macros"] }
strum_macros = "0.25.3"
pqef = { path = "../pqef" }
project = { path = "../project" }
terrain_player_client = { path = "../terrain_player_client" }
terrain_core = { path = "../terrain_core" }

rand = "0.8.5"
smallvec = "1.13.0"
futures-lite = "2.2.0"

noisy_bevy = "0.5.0"

bevy_obj = "0.12.0"

bevy_xpbd_3d = { version = "0.3.3", features = ["simd"] } # "debug-plugin"
bevy_xpbd_derive = "0.1.0"
bevy_replicon = "0.20.0"

# bevy_ecs_ldtk = "0.5.0"
# bevy_ecs_tilemap = "0.9.0"
# bevy_rapier2d = "0.20.0"

tracing-subscriber = { version = "0.3.18", features = [
    "registry",
    "env-filter",
    "json",
    "local-time",
] }
tracing-chrome = { version = "0.7.1", optional = true }
tracing-tracy = { version = "0.10.5", optional = true }
tracing-log = "0.2.0"
tracing-error = { version = "0.2.0", optional = true }
tracy-client = { version = "0.16", optional = true }
tracing-appender = { version = "0.2.3", features = [] }
serde_json = "1.0.111"
bevy-inspector-egui = "0.22.1"

[features]
default = ["trace_tracy"]
trace_chrome = ["bevy/trace_chrome"]
trace_tracy = ["bevy/trace_tracy", "dep:tracing-tracy"]