[package]
name = "ability"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
bevy-trait-query = "0.3.0"
bevy-trait-query-impl = "0.3.0"
lazy_static = "1.4.0"
smallvec = "1.11.0"

[[example]]
name = "base_attack"
path = "examples/base_attack.rs"
