[package]
name = "ability"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.11.2"
bevy-trait-query = "0.3.0"
bevy-trait-query-impl = "0.3.0"
once_cell = "1.18.0"
smallvec = "1.11.0"
layertag = { path = "../layertag" }

[[example]]
name = "ability"
path = "examples/ability/main.rs"
