
/*!
<auto-generated>
    This code was generated by a tool.
    Changes to this file may cause incorrect behavior and will be lost if
    the code is regenerated.
</auto-generated>
*/


use super::*;
use serde::Deserialize;

bitflags::bitflags!{    
    #[derive(Debug, Hash, Eq, PartialEq)]
    pub struct AccessFlag : u32 {
        const WRITE = 1;
        const READ = 2;
        const TRUNCATE = 4;
        const NEW = 8;
        ///位标记使用示例
        const READ_WRITE = WRITE|READ;
    }
}
#[derive(Debug)]
pub struct TestExcelBean1 {
    /// 最高品质
    pub x1: i32,
    /// 黑色的
    pub x2: String,
    /// 蓝色的
    pub x3: i32,
    /// 最差品质
    pub x4: f32,
}

impl TestExcelBean1{
    pub fn new(json: &serde_json::Value) -> Result<TestExcelBean1, LubanError> {
        let x1 = (json["x1"].as_i64().unwrap() as i32);
        let x2 = json["x2"].as_str().unwrap().to_string();
        let x3 = (json["x3"].as_i64().unwrap() as i32);
        let x4 = (json["x4"].as_f64().unwrap() as f32);
        
        Ok(TestExcelBean1 { x1, x2, x3, x4, })
    }
}

#[derive(Debug)]
pub struct TestExcelBean2 {
    /// 最高品质
    pub y1: i32,
    /// 黑色的
    pub y2: String,
    /// 蓝色的
    pub y3: f32,
}

impl TestExcelBean2{
    pub fn new(json: &serde_json::Value) -> Result<TestExcelBean2, LubanError> {
        let y1 = (json["y1"].as_i64().unwrap() as i32);
        let y2 = json["y2"].as_str().unwrap().to_string();
        let y3 = (json["y3"].as_f64().unwrap() as f32);
        
        Ok(TestExcelBean2 { y1, y2, y3, })
    }
}

#[derive(Debug)]
pub struct Shape {
}

impl Shape {
    pub fn new(json: &serde_json::Value) -> Result<std::sync::Arc<AbstractBase>, LubanError> {
        let type_id = json["$type"].as_str().unwrap();
        match type_id {
            "Circle" => Ok(std::sync::Arc::new(crate::test::Circle::new(json)?)),
            "Rectangle" => Ok(std::sync::Arc::new(crate::test::Rectangle::new(json)?)),
            _ => Err(LubanError::Bean(format!("Invalid type for Shape:{}", type_id)))
        }
    }
}

pub trait TShape {
}

impl crate::test::TShape for crate::test::Circle {
}

impl crate::test::TShape for crate::test::Rectangle {
}

impl<'a> GetBase<'a, &'a dyn crate::test::TShape> for AbstractBase {
    fn get_base(&'a self) -> Result<&'a dyn crate::test::TShape, LubanError> {
        let base: Result<&crate::test::Circle, _> = self.try_into();
        if let Ok(r) = base {
            return Ok(r);
        }
        let base: Result<&crate::test::Rectangle, _> = self.try_into();
        if let Ok(r) = base {
            return Ok(r);
        }

        Err(LubanError::Polymorphic(format!("Invalid type for Shape")))
    }
}

#[derive(Debug)]
#[derive(macros::TryIntoBase)]
pub struct Circle {
    /// 半径
    pub radius: f32,
}

impl Circle{
    pub fn new(json: &serde_json::Value) -> Result<Circle, LubanError> {
        let radius = (json["radius"].as_f64().unwrap() as f32);
        
        Ok(Circle { radius, })
    }
}

#[derive(Debug)]
#[derive(macros::TryIntoBase)]
pub struct Rectangle {
    /// 宽度
    pub width: f32,
    /// 高度
    pub height: f32,
}

impl Rectangle{
    pub fn new(json: &serde_json::Value) -> Result<Rectangle, LubanError> {
        let width = (json["width"].as_f64().unwrap() as f32);
        let height = (json["height"].as_f64().unwrap() as f32);
        
        Ok(Rectangle { width, height, })
    }
}


