[package]
name = "atom_terrain"
version = "0.1.0"
edition = "2024"
publish.workspace = true
license.workspace = true

[dependencies]
bevy = { workspace = true }
tracing = { workspace = true }
log = { workspace = true }
bytemuck = { workspace = true }
crossbeam = { workspace = true }

[dev-dependencies]

[[example]]
name = "chunk_loader"
path = "examples/chunk_loader.rs"

[lints]
workspace = true
