[package]
name = "terrain_player_client"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = { workspace = true }

enum-kinds = "0.5.1"
serde = "1.0.193"
serde_json = "1.0.108"
# tracing-appender = { version = "0.2.3", features = [] }
# tracing-serde = "0.1.3"
# tracing-test = "0.2.4"
tracing-subscriber = { version = "0.3.18", features = [] }