[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
smallvec = { workspace = true }
serde = { workspace = true }

project = { path = "../project" }
ability = { path = "../ability" }

datatables = { path = "../datatables" }
cfg = { path = "../datatables/gen/cfg" }
settings = { path = "../settings" }