[package]
name = "game"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
smallvec = { workspace = true }
serde = { workspace = true }
# big-brain = { workspace = true }
bitflags = { workspace = true }

project = { path = "../project" }
ability = { path = "../ability" }
datatables = { path = "../datatables" }
settings = { path = "../settings" }
settings_derive = { path = "../settings/settings_derive" }
