[package]
name = "cms"
version = "0.1.0"
edition = "2021"

[dependencies]
nalgebra = "0.32.2"
strum = { version ="0.24.1", features=["derive", "strum_macros"] }
strum_macros = "0.24.1"
tracing = { version = "0.1.37", features = [] }
tracing-log = "0.1.3"
